/**
 * Dünya üzerindeki tüm ülkelerin kapsamlı listesi.
 * 193 BM üyesi + 2 gözlemci devlet + yaygın tanınan bölgeler.
 * GeoJSON verisinde eksik olan ülkeleri sidebar'da gösterebilmek için kullanılır.
 */
export interface CountryData {
  name: string;
  iso: string;
}

export const ALL_COUNTRIES: CountryData[] = [
  { name: 'Afghanistan', iso: 'AF' },
  { name: 'Albania', iso: 'AL' },
  { name: 'Algeria', iso: 'DZ' },
  { name: 'Andorra', iso: 'AD' },
  { name: 'Angola', iso: 'AO' },
  { name: 'Antigua and Barbuda', iso: 'AG' },
  { name: 'Argentina', iso: 'AR' },
  { name: 'Armenia', iso: 'AM' },
  { name: 'Australia', iso: 'AU' },
  { name: 'Austria', iso: 'AT' },
  { name: 'Azerbaijan', iso: 'AZ' },
  { name: 'Bahamas', iso: 'BS' },
  { name: 'Bahrain', iso: 'BH' },
  { name: 'Bangladesh', iso: 'BD' },
  { name: 'Barbados', iso: 'BB' },
  { name: 'Belarus', iso: 'BY' },
  { name: 'Belgium', iso: 'BE' },
  { name: 'Belize', iso: 'BZ' },
  { name: 'Benin', iso: 'BJ' },
  { name: 'Bhutan', iso: 'BT' },
  { name: 'Bolivia', iso: 'BO' },
  { name: 'Bosnia and Herzegovina', iso: 'BA' },
  { name: 'Botswana', iso: 'BW' },
  { name: 'Brazil', iso: 'BR' },
  { name: 'Brunei', iso: 'BN' },
  { name: 'Bulgaria', iso: 'BG' },
  { name: 'Burkina Faso', iso: 'BF' },
  { name: 'Burundi', iso: 'BI' },
  { name: 'Cabo Verde', iso: 'CV' },
  { name: 'Cambodia', iso: 'KH' },
  { name: 'Cameroon', iso: 'CM' },
  { name: 'Canada', iso: 'CA' },
  { name: 'Cayman Islands', iso: '' },
  { name: 'Central African Republic', iso: 'CF' },
  { name: 'Chad', iso: 'TD' },
  { name: 'Chile', iso: 'CL' },
  { name: 'China', iso: 'CN' },
  { name: 'Colombia', iso: 'CO' },
  { name: 'Comoros', iso: 'KM' },
  { name: 'Cook Islands', iso: '' },
  { name: 'Congo', iso: 'CG' },
  { name: 'Costa Rica', iso: 'CR' },
  { name: 'Croatia', iso: 'HR' },
  { name: 'Cuba', iso: 'CU' },
  { name: 'Cyprus', iso: 'CY' },
  { name: 'Czech Republic', iso: 'CZ' },
  { name: 'Democratic Republic of the Congo', iso: 'CD' },
  { name: 'Denmark', iso: 'DK' },
  { name: 'Djibouti', iso: 'DJ' },
  { name: 'Dominica', iso: 'DM' },
  { name: 'Dominican Republic', iso: 'DO' },
  { name: 'East Timor', iso: 'TL' },
  { name: 'Ecuador', iso: 'EC' },
  { name: 'Egypt', iso: 'EG' },
  { name: 'El Salvador', iso: 'SV' },
  { name: 'Equatorial Guinea', iso: 'GQ' },
  { name: 'Eritrea', iso: 'ER' },
  { name: 'Estonia', iso: 'EE' },
  { name: 'Eswatini', iso: 'SZ' },
  { name: 'Ethiopia', iso: 'ET' },
  { name: 'Fiji', iso: 'FJ' },
  { name: 'Finland', iso: 'FI' },
  { name: 'France', iso: 'FR' },
  { name: 'Gabon', iso: 'GA' },
  { name: 'Gambia', iso: 'GM' },
  { name: 'Georgia', iso: 'GE' },
  { name: 'Germany', iso: 'DE' },
  { name: 'Ghana', iso: 'GH' },
  { name: 'Greece', iso: 'GR' },
  { name: 'Grenada', iso: 'GD' },
  { name: 'Guatemala', iso: 'GT' },
  { name: 'Guinea', iso: 'GN' },
  { name: 'Guinea-Bissau', iso: 'GW' },
  { name: 'Guyana', iso: 'GY' },
  { name: 'Haiti', iso: 'HT' },
  { name: 'Honduras', iso: 'HN' },
  { name: 'Hungary', iso: 'HU' },
  { name: 'Iceland', iso: 'IS' },
  { name: 'India', iso: 'IN' },
  { name: 'Indonesia', iso: 'ID' },
  { name: 'Iran', iso: 'IR' },
  { name: 'Iraq', iso: 'IQ' },
  { name: 'Ireland', iso: 'IE' },
  { name: 'Israel', iso: 'IL' },
  { name: 'Italy', iso: 'IT' },
  { name: 'Ivory Coast', iso: 'CI' },
  { name: 'Jamaica', iso: 'JM' },
  { name: 'Japan', iso: 'JP' },
  { name: 'Jordan', iso: 'JO' },
  { name: 'Kazakhstan', iso: 'KZ' },
  { name: 'Kenya', iso: 'KE' },
  { name: 'Kiribati', iso: 'KI' },
  { name: 'Kosovo', iso: 'XK' },
  { name: 'Kuwait', iso: 'KW' },
  { name: 'Kyrgyzstan', iso: 'KG' },
  { name: 'Laos', iso: 'LA' },
  { name: 'Latvia', iso: 'LV' },
  { name: 'Lebanon', iso: 'LB' },
  { name: 'Lesotho', iso: 'LS' },
  { name: 'Liberia', iso: 'LR' },
  { name: 'Libya', iso: 'LY' },
  { name: 'Liechtenstein', iso: 'LI' },
  { name: 'Lithuania', iso: 'LT' },
  { name: 'Luxembourg', iso: 'LU' },
  { name: 'Madagascar', iso: 'MG' },
  { name: 'Malawi', iso: 'MW' },
  { name: 'Malaysia', iso: 'MY' },
  { name: 'Maldives', iso: 'MV' },
  { name: 'Mali', iso: 'ML' },
  { name: 'Malta', iso: 'MT' },
  { name: 'Marshall Islands', iso: 'MH' },
  { name: 'Mauritania', iso: 'MR' },
  { name: 'Mauritius', iso: 'MU' },
  { name: 'Mexico', iso: 'MX' },
  { name: 'Micronesia', iso: 'FM' },
  { name: 'Moldova', iso: 'MD' },
  { name: 'Monaco', iso: 'MC' },
  { name: 'Mongolia', iso: 'MN' },
  { name: 'Montenegro', iso: 'ME' },
  { name: 'Morocco', iso: 'MA' },
  { name: 'Mozambique', iso: 'MZ' },
  { name: 'Myanmar', iso: 'MM' },
  { name: 'Namibia', iso: 'NA' },
  { name: 'Nauru', iso: 'NR' },
  { name: 'Nepal', iso: 'NP' },
  { name: 'Netherlands', iso: 'NL' },
  { name: 'New Zealand', iso: 'NZ' },
  { name: 'Nicaragua', iso: 'NI' },
  { name: 'Niger', iso: 'NE' },
  { name: 'Nigeria', iso: 'NG' },
  { name: 'North Korea', iso: 'KP' },
  { name: 'North Macedonia', iso: 'MK' },
  { name: 'Norway', iso: 'NO' },
  { name: 'Oman', iso: 'OM' },
  { name: 'Pakistan', iso: 'PK' },
  { name: 'Palau', iso: 'PW' },
  { name: 'Palestine', iso: 'PS' },
  { name: 'Panama', iso: 'PA' },
  { name: 'Papua New Guinea', iso: 'PG' },
  { name: 'Paraguay', iso: 'PY' },
  { name: 'Peru', iso: 'PE' },
  { name: 'Philippines', iso: 'PH' },
  { name: 'Poland', iso: 'PL' },
  { name: 'Portugal', iso: 'PT' },
  { name: 'Qatar', iso: 'QA' },
  { name: 'Romania', iso: 'RO' },
  { name: 'Russia', iso: 'RU' },
  { name: 'Rwanda', iso: 'RW' },
  { name: 'Saint Kitts and Nevis', iso: 'KN' },
  { name: 'Saint Lucia', iso: 'LC' },
  { name: 'Saint Vincent and the Grenadines', iso: 'VC' },
  { name: 'Samoa', iso: 'WS' },
  { name: 'San Marino', iso: 'SM' },
  { name: 'Sao Tome and Principe', iso: 'ST' },
  { name: 'Saudi Arabia', iso: 'SA' },
  { name: 'Senegal', iso: 'SN' },
  { name: 'Serbia', iso: 'RS' },
  { name: 'Seychelles', iso: 'SC' },
  { name: 'Sierra Leone', iso: 'SL' },
  { name: 'Singapore', iso: 'SG' },
  { name: 'Slovakia', iso: 'SK' },
  { name: 'Slovenia', iso: 'SI' },
  { name: 'Solomon Islands', iso: 'SB' },
  { name: 'Somalia', iso: 'SO' },
  { name: 'South Africa', iso: 'ZA' },
  { name: 'South Korea', iso: 'KR' },
  { name: 'South Sudan', iso: 'SS' },
  { name: 'Spain', iso: 'ES' },
  { name: 'Sri Lanka', iso: 'LK' },
  { name: 'Sudan', iso: 'SD' },
  { name: 'Suriname', iso: 'SR' },
  { name: 'Sweden', iso: 'SE' },
  { name: 'Switzerland', iso: 'CH' },
  { name: 'Syria', iso: 'SY' },
  { name: 'Taiwan', iso: 'TW' },
  { name: 'Tajikistan', iso: 'TJ' },
  { name: 'Tanzania', iso: 'TZ' },
  { name: 'Thailand', iso: 'TH' },
  { name: 'Togo', iso: 'TG' },
  { name: 'Tonga', iso: 'TO' },
  { name: 'Trinidad and Tobago', iso: 'TT' },
  { name: 'Tunisia', iso: 'TN' },
  { name: 'Turkey', iso: 'TR' },
  { name: 'Turkmenistan', iso: 'TM' },
  { name: 'Tuvalu', iso: 'TV' },
  { name: 'Uganda', iso: 'UG' },
  { name: 'Ukraine', iso: 'UA' },
  { name: 'United Arab Emirates', iso: 'AE' },
  { name: 'United Kingdom', iso: 'GB' },
  { name: 'United States of America', iso: 'US' },
  { name: 'Uruguay', iso: 'UY' },
  { name: 'Uzbekistan', iso: 'UZ' },
  { name: 'Vanuatu', iso: 'VU' },
  { name: 'Vatican City', iso: 'VA' },
  { name: 'Venezuela', iso: 'VE' },
  { name: 'Vietnam', iso: 'VN' },
  { name: 'Yemen', iso: 'YE' },
  { name: 'Zambia', iso: 'ZM' },
  { name: 'Zimbabwe', iso: 'ZW' },
];
